### PR TITLE
Setup Hello Microverse Project 

### PR DESCRIPTION
**Pull request by MelissaKamau**
This is a setup Hello Microverse Project with HTML and CSS linter. Branches with different base branches are in place 
I have fixed the errors on the style.css sheet. It includes using appropriate spacing which in this case is 2. I have also reinstalled the linters to remove the unknown rule function invalid error. Lastly, I have customized the README template and committed the changes.

### CODE REVIEW

**Review by ha-manel — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES ♻️

## Hi @MelissaKamau 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  



## Highlights:  
* Meaningful commit messages ✔️ 
* Github flow is followed correctly ✔️ 
* .gitignore is setup correctly ✔️ 

## Required Changes:
- [ ] Kindly update your pull request title, it should be descriptive of what's inside the pull request and we should avoid generic titles that will get us confused later. An example would be "Setup Hello Microverse Project" 👍 
- [ ] Kindly add a pull request description to your pull request, it should have a descriptive summary of all the changes that have been made in this pull request.
- [ ] Kindly use the following [template](https://github.com/microverseinc/readme-template) for your README file. Please copy the content of the file and fill out the sections with information related to your project for professional documentation ✨ 
- [ ] Kindly fix the linter errors that you've got, you should always have green linter checks before you submit the pull request for review to avoid invalidation 👍 
- [ ] From now on, kindly choose the branch's name more carefully, it should have the name of the action made in the branch to make it descriptive enough, example: "setup-project" 💯 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MelissaKamau** [comment]
Thank you for the update. Will make changes accordingly.

**Comment by MelissaKamau** [comment]
> Setup Hello Microverse Project
I have fixed the errors on the style.css sheet. It includes using appropriate spacing which in this case is 2. I have also reinstalled the linters to remove the unknown rule function calc no invalid error.  Lastly, I have customized the README template and committed the changes.

**Comment by MelissaKamau** [comment]
I have fixed the errors on the style.css sheet. It includes using appropriate spacing which in this case is 2. I have also reinstalled the linters to remove the unknown rule function calc no invalid error. Lastly, I have customized the README template and committed the changes.

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @MelissaKamau , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.



 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As requested by the previous code reviewer,  Please kindly add a pull request description to your pull request, it should have a descriptive summary of all the changes that have been made in this pull request. But as you can see you did not add any description to your pull request

Screenshot from 2022-11-29 14-50-21

To edit your pull request, click on the three so icon and you will see the edit option

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by roshan-bajgain — APPROVED** [review]
Hi @MelissaKamau, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
